image: Visual Studio 2017
before_build:
  - nuget restore
configuration:
  - Release
build:
  parallel: true
  project: RSMaster.sln
after_build:
  7z a RSMaster.zip %APPVEYOR_BUILD_FOLDER%\obj\Release\*.dll
artifacts:
  - path: \RSMaster.zip
    name: RSMaster