image: Visual Studio 2017
configuration:
  - Release
before_build:
  - nuget restore
build:
  parallel: true
  project: RSMaster.sln
after_build:
  7z a RSMaster.zip C:\projects\rsmaster\RSMaster\bin\Release
artifacts:
  - path: C:\RSMaster.zip
    name: RSMaster