//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-mail.com
        ///007addict.com
        ///020.co.uk
        ///027168.com
        ///0815.ru
        ///0815.su
        ///0clickemail.com
        ///0sg.net
        ///0wnd.net
        ///0wnd.org
        ///1033edge.com
        ///10mail.org
        ///10minutemail.co.za
        ///10minutemail.com
        ///11mail.com
        ///123-m.com
        ///123.com
        ///123box.net
        ///123india.com
        ///123mail.cl
        ///123mail.org
        ///123qwe.co.uk
        ///126.com
        ///126.net
        ///138mail.com
        ///139.com
        ///150mail.com
        ///150ml.com
        ///15meg4free.com
        ///163.com
        ///16mail.com
        ///188.com
        ///189.cn
        ///1auto.com
        ///1ce.us
        ///1chuan.com
        ///1colony.com
        ///1coolplace.com
        ///1email.eu
        ///1freeemail.com
        ///1fsdfdsfsdf.tk
        ///1funplace.com
        ///1internetdrive.com
        ///1mail.ml
        ///1mail.net
        ///1me.n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emails {
            get {
                return ResourceManager.GetString("emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaren
        ///Aarika
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addia
        ///Addie
        ///Addy
        ///Adel
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adey
        ///Adi
        ///Adiana
        ///Adina
        ///Adora
        ///Adore
        ///Adoree
        ///Adorne
        ///Adrea
        ///Adria
        ///Adriaens
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriel
        ///Aeriela
        ///Aeriell
        ///Afton
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Agathe
        ///Aggi
        ///Aggie
        ///Aggy
        ///Ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
    }
}
